server:
  port: 8558
spring:
  mail:
    host: in-v3.mailjet.com
    port: 587
    username: ${MAIL_JET_API_KEY}
    password: ${MAIL_JET_API_SECRET}

    properties:
      mail:
        smtp:
          auth: true
          starts-sl:
            enable: true
            required: true
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: "Meetello"


twilio:
  accountSid: ${TWILIO_API_KEY}
  authToken: ${TWILIO_AUTH_KEY}
  phoneNumber: ${TWILIO_PHONE_NUMBER}


jwt:
  key: ${JWT}

hash:
  key: ${HASH_KEY}

